services:
  sena-postgres:
    image: postgres:16
    container_name: sena-postgres
    environment:
      POSTGRES_USER: ${POSTGRES_USER:-postgres}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-postgres}
      POSTGRES_DB: ${POSTGRES_DB:-mydatabase}
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - '5432:5432'
    restart: unless-stopped
  sena-chat-history:
    image: redis:latest
    container_name: sena-chat-history
    ports:
      - '6379:6379'
    restart: unless-stopped
    environment:
      REDIS_PASSWORD: ${REDIS_PASSWORD:-password}
    volumes:
      - sena-chat-history:/data

volumes:
  postgres_data:
  sena-chat-history:
