services:
  sena-postgres:
    image: postgres:16
    container_name: sena-postgres
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - '${POSTGRES_PORT}:5432'
    restart: unless-stopped
  sena-chat-history:
    image: redis:latest
    container_name: sena-chat-history
    ports:
      - '6379:6379'
    restart: unless-stopped
    environment:
      REDIS_PASSWORD: ${REDIS_PASSWORD}
    volumes:
      - sena-chat-history:/data

volumes:
  postgres_data:
  sena-chat-history:
